name: video_watermark
description: A Flutter package with simple tool to Watermark in video with Trim and more.
homepage: https://github.com/ededin/video_watermark

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: 4.5.1-LTS
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.0

platforms:
  android:
  ios:
  macos:
